"use server";

import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server-auth";
import { getProductBySlug } from "@/lib/products";
import { sendNewOrderEmail, sendOrderConfirmationEmail } from "@/lib/notify";
import { checkPincode } from "@/lib/delivery";
import { getStoreStatus } from "@/lib/store-status";
import {
  hasErrors,
  validateOrder,
  type FieldErrors,
  type OrderInput,
} from "@/lib/order-schema";

export type OrderState = { errors?: FieldErrors; formError?: string };

/**
 * Create an order request.
 *
 * Two things are deliberately NOT taken from the form:
 *   - the customer id, which comes from the verified session, so an
 *     order can never be filed under someone else's account;
 *   - the price, which is re-read from the database, so editing the
 *     hidden price field in devtools changes nothing.
 */
export async function placeOrder(
  _prev: OrderState,
  formData: FormData
): Promise<OrderState> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { formError: "Your sign-in expired. Please sign in and try again." };
  }


  // The buttons are hidden while closed, but a form could still be
  // submitted from a stale page. This is the check that actually stops
  // an order arriving after the kitchen has shut.
  const store = await getStoreStatus();
  if (!store.acceptingOrders) {
    return { formError: store.message };
  }

  const slug = str(formData.get("slug"));
  const product = await getProductBySlug(slug);
  if (!product) {
    return { formError: "That cake is no longer available." };
  }

  const input: OrderInput = {
    variantLabel: str(formData.get("variantLabel")),
    quantity: Number(formData.get("quantity") ?? 1),
    colour: str(formData.get("colour")),
    cakeMessage: str(formData.get("cakeMessage")).trim(),
    specialInstructions: str(formData.get("specialInstructions")).trim(),
    fulfillmentType:
      formData.get("fulfillmentType") === "delivery" ? "delivery" : "pickup",
    address: str(formData.get("address")).trim(),
    landmark: str(formData.get("landmark")).trim(),
    city: str(formData.get("city")).trim(),
    pincode: str(formData.get("pincode")).trim(),
    latitude: numOrNull(formData.get("latitude")),
    longitude: numOrNull(formData.get("longitude")),
    preferredDate: str(formData.get("preferredDate")),
    preferredTime: str(formData.get("preferredTime")),
    contactName: str(formData.get("contactName")).trim(),
    contactPhone: str(formData.get("contactPhone")).trim(),
  };

  const errors = validateOrder(input);
  if (hasErrors(errors)) return { errors };

  // Re-check serviceability on the server. The browser already checked,
  // but that result can't be trusted — someone could submit delivery to
  // an area we don't cover, and we'd only find out after promising it.
  if (input.fulfillmentType === "delivery") {
    const area = await checkPincode(input.pincode);
    if (!area.serviceable) {
      return {
        errors: {
          pincode:
            "We don't deliver to that pincode. Please choose pickup, or arrange your own courier.",
        },
      };
    }
  }

  // Price comes from the database, never the form. If the chosen size
  // isn't one this product actually offers, fall back to its base price
  // rather than trusting whatever was submitted.
  const chosen = product.variants.find((v) => v.label === input.variantLabel);
  const unitPrice = chosen ? chosen.price : product.price;
  const variantLabel = chosen ? chosen.label : null;

  // Ensure a profile row exists — a Google sign-up may never have
  // visited the account page, and orders reference it.
  await supabase
    .from("website_customers")
    .upsert(
      { id: user.id, full_name: input.contactName, phone: input.contactPhone },
      { onConflict: "id" }
    );

  const isDelivery = input.fulfillmentType === "delivery";

  const { data, error } = await supabase
    .from("orders")
    .insert({
      // order_no is generated by the database sequence (migration 0010)
      customer_id: user.id,
      product_id: product.id,
      product_name: product.name,
      variant: {
        size: variantLabel,
        colour: input.colour || null,
      },
      variant_label: variantLabel,
      quantity: input.quantity,
      unit_price: unitPrice,
      estimated_total: unitPrice * input.quantity,
      cake_message: input.cakeMessage || null,
      special_instructions: input.specialInstructions || null,
      fulfillment_type: input.fulfillmentType,
      address: isDelivery ? input.address || null : null,
      landmark: isDelivery ? input.landmark || null : null,
      city: isDelivery ? input.city || null : null,
      pincode: isDelivery ? input.pincode || null : null,
      latitude: isDelivery ? input.latitude : null,
      longitude: isDelivery ? input.longitude : null,
      preferred_date: input.preferredDate,
      preferred_time: input.preferredTime || null,
      contact_name: input.contactName,
      contact_phone: input.contactPhone,
      contact_email: user.email ?? null,
      status: "received",
    })
    .select("order_no")
    .single();

  if (error) {
    console.error("[placeOrder]", error);
    return {
      formError:
        "We couldn't submit your order right now. Please try again in a moment.",
    };
  }

  // Notifications are a side effect, never a precondition. The order is
  // already saved; if email is misconfigured or Gmail is down, the
  // customer must still get their confirmation page. Failures are
  // swallowed here and logged inside the notifier.
  const emailData = {
    orderNo: data.order_no,
    productName: product.name,
    variantLabel,
    quantity: input.quantity,
    estimatedTotal: unitPrice * input.quantity,
    customerName: input.contactName,
    customerPhone: input.contactPhone,
    customerEmail: user.email ?? null,
    fulfillmentType: input.fulfillmentType,
    preferredDate: input.preferredDate,
    preferredTime: input.preferredTime || null,
    cakeMessage: input.cakeMessage || null,
    specialInstructions: input.specialInstructions || null,
    address: isDelivery
      ? [input.address, input.landmark, input.city, input.pincode]
          .filter(Boolean)
          .join(", ") || null
      : null,
    mapsLink:
      isDelivery && input.latitude && input.longitude
        ? `https://www.google.com/maps/search/?api=1&query=${input.latitude},${input.longitude}`
        : null,
  };

  await Promise.allSettled([
    sendNewOrderEmail(emailData),
    sendOrderConfirmationEmail(emailData),
  ]);

  // Redirect on success so a refresh can't resubmit the order.
  redirect(`/account/orders?placed=${encodeURIComponent(data.order_no)}`);
}

function str(v: FormDataEntryValue | null): string {
  return typeof v === "string" ? v : "";
}

function numOrNull(v: FormDataEntryValue | null): number | null {
  const n = Number(v);
  return typeof v === "string" && v !== "" && Number.isFinite(n) ? n : null;
}
