-- ============================================================
-- Order pricing, delivery location, and order numbers
--
-- Additive. New columns and a sequence; no existing column is
-- changed and no row is modified.
-- ============================================================

begin;

-- ── 1. Price snapshot ──────────────────────────────────────────
-- The price is recorded ON the order at the moment it is placed.
-- Prices in `products` change over time, so reading them later would
-- silently reprice historical orders and disagree with what the
-- customer was actually shown.
alter table orders
  add column if not exists variant_label   text,
  add column if not exists unit_price      numeric(10,2),
  add column if not exists estimated_total numeric(10,2);

comment on column orders.unit_price is
  'Price of the chosen size at the time of ordering. Snapshot — never recalculated from products.';
comment on column orders.estimated_total is
  'unit_price x quantity, before any add-ons or delivery charge. The owner confirms the final figure when invoicing.';

-- ── 2. Delivery location ───────────────────────────────────────
-- A typed address is often ambiguous for home delivery. When the
-- customer shares their location we keep the coordinates too, so the
-- owner gets an exact pin rather than guessing from a street name.
alter table orders
  add column if not exists latitude  numeric(9,6),
  add column if not exists longitude numeric(9,6);

comment on column orders.latitude is
  'Optional GPS latitude, captured only if the customer taps "use my location". Paired with longitude to form a maps link in Leo Billing.';

-- ── 3. Order numbers ───────────────────────────────────────────
-- Generated by the database rather than in application code: two
-- customers ordering in the same second would otherwise be able to
-- generate the same number, and order_no is unique.
create sequence if not exists order_no_seq start 1001;

alter table orders
  alter column order_no set default ('AC' || nextval('order_no_seq')::text);

commit;

-- ── Verify ──────────────────────────────────────────────────────
-- select column_name, data_type from information_schema.columns
--   where table_name = 'orders' order by ordinal_position;
